CREATE DATABASE test_task_db;
--Не совсем понимаю зачем тут хранимые процедуры. Entity Framework позволяет работать с таблицами проще
CREATE TABLE categories(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(20) NOT NULL UNIQUE,
	hex_color varchar(7) CHECK (hex_color ~* '^#[a-f0-9]{6}$')
);

CREATE TABLE events(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(200) NOT NULL,
	date TIMESTAMP,
	category_id int,
	FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE PROCEDURE get_event(
	_id int,
	out _name varchar(200),
	out _date timestamp,
	out _category_id int,
	out _category_name varchar(20),
	out _category_color varchar(7)
)
AS
$$
BEGIN
SELECT e.name,e.date,e.category_id,c.name,c.hex_color FROM events e LEFT JOIN categories c ON e.category_id=c.id INTO _name,_date,_category_id,_category_name,_category_color WHERE e.id=_id ; 
END;
$$
LANGUAGE plpgsql

CREATE PROCEDURE insert_event(
	out _id int,
	inout _name varchar(200),
	inout _date timestamp,
	inout _category_id int
)
AS $$
BEGIN
WITH rows AS 
(INSERT INTO events(name,date,category_id) VALUES (_name, _date,_category_id) RETURNING id,name,date,category_id)
SELECT id,name,date,category_id FROM rows INTO _id,_name,_date,_category_id;
END;
$$
LANGUAGE plpgsql;

CREATE PROCEDURE modify_event(
	_id int,
	_name varchar(200),
	_date timestamp,
	_category_id int
)
AS $$
UPDATE events SET name=_name,date=_date,category_id=_category_id WHERE id=_id;
$$
LANGUAGE sql;


CREATE PROCEDURE delete_event(
	eventId int
)
as $$
DELETE FROM events WHERE id=eventId
$$
LANGUAGE sql;

CREATE PROCEDURE insert_category(
	out _id int,
	inout _name varchar(20),
	inout _hex_color varchar(7)
)
AS $$
BEGIN
WITH rows AS 
(INSERT INTO categories(name,hex_color) VALUES (_name, _hex_color) RETURNING id,name,hex_color)
SELECT id,name,hex_color FROM rows INTO _id,_name,_hex_color;
END;
$$
LANGUAGE plpgsql;

CREATE PROCEDURE modify_category(
	in _id int,
	_name varchar(20),
	_hex_color varchar(7)
)
AS $$
UPDATE categories SET name=_name,hex_color=_hex_color WHERE id=_id;
$$
LANGUAGE sql;

CREATE PROCEDURE delete_category(
	category_id int
)
as $$
DELETE FROM categories WHERE id=category_id
$$
LANGUAGE sql;

CREATE PROCEDURE get_category(
	inout _id int,
	out _name varchar(20),
	out _hex_color varchar(7)
)
AS $$
BEGIN
SELECT id,name,hex_color FROM categories WHERE id=_id INTO _id,_name,_hex_color;
END;
$$
LANGUAGE plpgsql;

INSERT INTO categories(name,hex_color) VALUES ('Срочно','#80b6df');
INSERT INTO categories(name,hex_color) VALUES ('Важно','#f81c1c');

